# Objectives:
# Estimate the posterior distribution of the parameters that explain statistical differences between clases.
# The clasess to investigate are:
# (1) Differences between species within the same country or region.
# (2) Differences between countries, within each species.
# These functions herein will select a balanced sample of species within the region.
# Conditions for the data subset:
# A balanced sample of data will have the same number of observations for all species.
# The data subset must contain similar ammount of zeros and ones in the subset.

# 1. SET PATH TO WORKING DIRECTORY
# path = "PATH TO THE DATA"

setwd(path)
# 1. Read data
# D = read.csv("Global_AMR_Final_Database_2_corrected_coordinates 1.csv")
# D = D[is.na(d$year)==F,] # Eliminate data without year

# 2. Select Regions
require(rgdal)
land = readOGR("https://gegp01.github.io/ServSoc/countries.geojson")

# 2.1 Read species phylogeny
require(ape)
V = read.tree("https://gegp01.github.io/AMR/SpeciesLevelTree.newick")
nms_tree = V$tip.label

# DATA
# Make a back up of the original data.
#d.back = D 

# 2.2 Names of the antibiotics
antibiotics = c("aminoglycoside", "betalactamics", "colistin", "fosfomycin", "glycopeptide", "macrolide"
                , "oxazolidinone", "phenicol", "quinolone", "rifampicin", "sulfo0mide", "tetracycline", "trimethoprim")

##############################################
##############################################

# 3 SUBSET MAKER
# FUNCTION TO MAKE SUBSETS OF a period of time from t.min to 2022, and select species with a minimum sample size (s.min).

# 3.1 DETERMINE THE TIME WINDOW (YEAR)
t.min = 2010

# 3.2 DETERMINE MINIMUM NUMBER OF SAMPLES PER SPECIES
s.min = 600

# FUNCTION TO GENERATE 
f1 = function(t.min, s.min) {
  X = table(d$species)
  taxa = names(X[X>=s.min]) # select taxa
  d.sample = d[is.na(match(d$species, taxa))==F,]
                 
  # SUBSET OF CURRENT TIMES (las 10 years)
  d.sample.time = d.sample[d.sample$year>=t.min,]
                 
  # WORKING DATASET
  d.sample.time
  }

# READ DATA AS d
d = read.csv("Global_AMR_Final_Database_2_corrected_coordinates 1.csv")
d = d[is.na(d$year)==F,] # Eliminate data without year
# 2.2 Change name of antibiotic family
names(d)[names(d)=="amino"]<-"aminoglycoside"

# RUN f1 TO GENERATE A WORKING SUBSET OF THE DATA
d.w = f1(t.min=t.min, s.min=s.min)

# 4. SELECT DATA IN d.w FROM A SINGLE COUNTRY
countries = unique(d.w$country)
continent = unique(d.w$continent)

# HERE A LIST CONTAINING ALL COUNTRIES IN d.w CAN BE GENERATED BY FUNCTION f2
# d.c = d.w[d.w$country==countries[1]]
f2 = function(x){d.w[d.w$country==countries[x],]}                  
C = lapply(1:length(countries), f2)

f3 = function(x){d.w[d.w$continent==continent[x],]}                  
CONT = lapply(1:length(continent), f3)

# Select countries with a minimum sample size for each of the species


f.sample = function(x){ # x = number of countries
  Q = table(X[[x]]$specie)>10 # 10 is minimum number of observations per species
  
  idx = names(Q[Q==T]) # NAMES OF SPECIES WITH SAMPLE ABOVE N min.
  X[[x]][is.na(match(X[[x]]$species, idx))==F,] # q is the dataframe with species that have > 10 observations.
  
}

X = C
q = lapply(1:length(X), f.sample) # LIST OF COUNTRIES (C) WITH A LIST OF SPECIES DATA, WITH > 10 samples.

# RANDMLY SELECT ONE OBSERVATION PER SPECIES
#  nms = unique(q$species) # names of species in the data subset
#  require(ape)
#  v = keep.tip(V, nms) # phylogeny with species within the data subset
  # SELECT A RANDOM OBSERVATION WITHIN SAMPLES OF EACH FACTOR LEVEL (species) 
  #  https://stackoverflow.com/questions/40715863/select-a-random-sample-within-levels-of-a-factor-unequal-stratum-size-per-facto
  
#  w = split.data.frame(X[[x]], X[[x]]$specie) # x = number of species

# MAP THE FUNCTION?

  fx = function(x){
    q = w[[x]]
    W = split.data.frame(q, q$specie) # x = number of species 
    sample(q$id, 1)}
  
  w2 = do.call(fx, w)  ###### IN DEVELOPMENT! This must be a list of ids one per species. This will be used to select the subset from X[[x]]
  q[is.na(match(q$id, unlist(w2))==F,]  
  }

V = read.tree("https://gegp01.github.io/AMR/SpeciesLevelTree.newick")
X = C  


###################
ok = sapply(1:length(X), f.sampleX)
C2 = C[ok]
f3 = function(x){unique(C2[[x]]$country)}
sapply(1:17, f3)

# NOTE! THE SAMPLES ARE VERY UNBALANCED! FEW SAMPLES OF A SPECIES AND A LOT FROM ANOTHER SPECIES.

# 5. PERFORM BOOTSTRAPPING ON EACH DATASELT IN THE LIST C
# 5.1. Determine type of analysis
f.glm = function(x){
                    require(MCMCglmm)
                    prior = X
                    MCMCglmm(AMR~species + 1|taxa, data = D_)
                    }
# 5.2. Function to iterate the analysis in f.glm()                 
f.bootstrap = function(x){
  idx = paste("x", 1:nrow(d.c))
  D_ = split.data.frame(C[[1]], C[[1]]$species) # SPLIT DATAFRAME BY SPECIES WITHIN THE COUNTRY IN C[[x]]
  
  # RUN f.glm WITHIN THIS FUNCTION.

}
                 
                 
                 
