# Objectives:
# Estimate the posterior distribution of the parameters that explain statistical differences between clases.
# The clasess to investigate are:
# (1) Differences between species within the same country or region.
# (2) Differences between countries, within each species.
# These functions herein will select a balanced sample of species within the region.
# Conditions for the data subset:
# A balanced sample of data will have the same number of observations for all species.
# The data subset must contain similar ammount of zeros and ones in the subset.


# 1. SET PATH TO WORKING DIRECTORY
# path = "PATH TO THE DATA"

setwd(path)
# 1. Read data
# D = read.csv("Global_AMR_Final_Database_2_corrected_coordinates 1.csv")
# D = D[is.na(d$year)==F,] # Eliminate data without year

# 2. Select Regions
require(rgdal)
land = readOGR("https://gegp01.github.io/ServSoc/countries.geojson")

# 2.1 Read species phylogeny
require(ape)
V = read.tree("https://gegp01.github.io/AMR/SpeciesLevelTree.newick")
nms_tree = V$tip.label

# DATA
# Make a back up of the original data.
#d.back = D 

# 2.2 Names of the antibiotics
antibiotics = c("aminoglycoside", "betalactamics", "colistin", "fosfomycin", "glycopeptide", "macrolide"
                , "oxazolidinone", "phenicol", "quinolone", "rifampicin", "sulfo0mide", "tetracycline", "trimethoprim")

##############################################
##############################################

# 3 SUBSET MAKER
# FUNCTION TO MAKE SUBSETS OF a period of time from t.min to 2022, and select species with a minimum sample size (s.min).

# 3.1 DETERMINE THE TIME WINDOW (YEAR)
t.min = 2010

# 3.2 DETERMINE MINIMUM NUMBER OF SAMPLES PER SPECIES
s.min = 600

# FUNCTION TO GENERATE 
f1 = function(t.min, s.min) {
  X = table(d$species)
  taxa = names(X[X>=s.min]) # select taxa
  d.sample = d[is.na(match(d$species, taxa))==F,]
                 
  # SUBSET OF CURRENT TIMES (las 10 years)
  d.sample.time = d.sample[d.sample$year>=t.min,]
                 
  # WORKING DATASET
  d.sample.time
  }

# READ DATA AS d
d = read.csv("Global_AMR_Final_Database_2_corrected_coordinates 1.csv")
d = d[is.na(d$year)==F,] # Eliminate data without year
# 2.2 Change name of antibiotic family
names(d)[names(d)=="amino"]<-"aminoglycoside"


# RUN f1 TO GENERATE A WORKING SUBSET OF THE DATA (at t.min = 2010 and s.min = 10)
d.w = f1(t.min=t.min, s.min=s.min)
d.w$idx = paste("x", 1:nrow(d.w), sep="_")
row.names(d.w) = d.w$idx

# 4. SELECT DATA IN d.w FROM A SINGLE COUNTRY
countries = unique(d.w$country)
continent = unique(d.w$continent)

# HERE A LIST CONTAINING ALL COUNTRIES IN d.w CAN BE GENERATED BY FUNCTION f2
# d.c = d.w[d.w$country==countries[1]]
f2 = function(x){d.w[d.w$country==countries[x],]}                  
C = lapply(1:length(countries), f2)

f3 = function(x){d.w[d.w$continent==continent[x],]}                  
CONT = lapply(1:length(continent), f3)

# Select countries with a minimum sample size for each of the species

f.sample = function(x){ # x = number of countries
  Q = table(X[[x]]$specie)>10 # 10 is minimum number of observations per species
  idx = names(Q[Q==T]) # NAMES OF SPECIES WITH SAMPLE ABOVE N min.
  q = X[[x]][is.na(match(X[[x]]$species, idx))==F,] # q is the dataframe with species that have > 10 observations.
  q = q[rowSums(q[,antibiotics])>0,] # SELECT ROWS WITH AT LEAST 1 RESITANCE, NO ZERO rowSums()
#  q = q[sapply(1:length(q), f4)]
#  z = ifelse(nrow(q)==0, F, T)
#  row.names(q) = paste("x", 1:nrow(q), sep="_")
  q
}

X = C
#row.names(X) = paste("x", nrow(X), sep="_")
q2 = lapply(1:length(X), f.sample) # LIST OF COUNTRIES (C) WITH A LIST OF SPECIES DATA, WITH > 10 samples; AND NO rowSums = ZERO.

# ELIMNIATE COUNTRIES WITH NO SAMPLES. (All species have less than 10 obs) 
f4 = function(x){nrow(q2[[x]])>0}
q = q2[sapply(1:length(q2), f4)]

# RANDMLY SELECT ONE OBSERVATION PER SPECIES
f.sample.taxa = function(y) {sample(y$idx, 1)}

fx = function(x) {w = split(q[[x]], q[[x]]$species) # x = number of species
    lapply(w, f.sample.taxa)}

# LIST OF ONE RANDOM SAMPLE PER COUNTRY/REGION)
Z=lapply(1:length(q), fx)          

# SELECT samples in Z with more than 10 species
z = Z[lapply(Z, length)>10]

# DATA WITH MORE THAN 10 SPECIES
D=d.w[is.na(match(d.w$idx, unlist(z)))==F,]
unique(D$country) # "Australia" "China"     "UK"        "USA" 
unique(D$specie) # 20 species

# 2. Phylogenetic Clustering
require(ape)
V = read.tree("https://gegp01.github.io/AMR/SpeciesLevelTree.newick")

# Prune tree
tr = keep.tip(V, gsub(" ", "_", names(z[[1]])))
plot(tr)

f.phylo = function(x) {tr = keep.tip(V, gsub(" ", "_", names(z[[x]])))}
f.data = function(x) {d.w[is.na(match(d.w$idx, z[[x]]))==F, c(antibiotics, "country")]}

tr = lapply(1:length(z), f.phylo)
D =  lapply(1:length(z), f.data)

# PLOT TREES
svg("sample_trees.svg")
  par(mfrow=c(2,2))
  plot(tr[[1]], main=unique(D[[1]]$country))
  plot(tr[[2]], main=unique(D[[2]]$country))
  plot(tr[[3]], main=unique(D[[3]]$country))
  plot(tr[[4]], main=unique(D[[4]]$country))
dev.off()

#######





###################
ok = sapply(1:length(X), f.sampleX)
C2 = C[ok]
f3 = function(x){unique(C2[[x]]$country)}
sapply(1:17, f3)

# NOTE! THE SAMPLES ARE VERY UNBALANCED! FEW SAMPLES OF A SPECIES AND A LOT FROM ANOTHER SPECIES.

# 5. PERFORM BOOTSTRAPPING ON EACH DATASELT IN THE LIST C
# 5.1. Determine type of analysis
f.glm = function(x){
                    require(MCMCglmm)
                    prior = X
                    MCMCglmm(AMR~species + 1|taxa, data = D_)
                    }
# 5.2. Function to iterate the analysis in f.glm()                 
f.bootstrap = function(x){
  idx = paste("x", 1:nrow(d.c))
  D_ = split.data.frame(C[[1]], C[[1]]$species) # SPLIT DATAFRAME BY SPECIES WITHIN THE COUNTRY IN C[[x]]
  
  # RUN f.glm WITHIN THIS FUNCTION.

}
                 
                 
                 
