# PHYLOGENETOC STRUCTURE

# Script to assess the phylogenetic signar in the AMR of a set of bacteria.

# RUN ANALYSES WITH THE ELEMENTS IN THE LIST G, GENERATED BY THE SCRIPT: random_forest.R
# class(G[["bootstrap loop"]][[1]][["1 = data or 2 = tree"]][["country"]])  


AMR = AMR.USA

AMR = names(G[[1]][[1]][[1]][[1]][,1:13])
com = G[[1]][[1]][[1]][[1]][,AMR]
row.names(com) = gsub(" ", "_", G[[1]][[1]][[1]][[1]]$species)
tr = G[[1]][[1]][[2]][[1]]

require(picante)
phylostruct(t(com), tr, env=NULL, metric="psc", 
  null.model=c("frequency", "richness","independentswap","trialswap"),
  runs=100, it=1000, alpha=0.05, fam="binomial")


